import React from 'react'
import Navbar from '../SharedComponents/Navbar'
import Hero from './Hero'
import Categories from './Categories'
import Main from './Main'
import GetInTouch from './GetInTouch'
import SaleSection from './SaleSection'
import Footer from '../SharedComponents/footer'
import LoginForm from './LoginForm'
import Signup from './Signup'
import AboutPage from '../pages/AboutPage'
export {Navbar,Hero,Categories,Main,GetInTouch,SaleSection,Footer,LoginForm,Signup,AboutPage}
