import React from 'react'
import Navbar from '../components/SharedComponents/Navbar'
import Hero from './Hero'
import Categories from './Categories'
import Main from './Main'
import GetInTouch from './GetInTouch'
import SaleSection from './SaleSection'
import Footer from '../components/SharedComponents/footer'
import LoginForm from './LoginForm'
import Signup from './Signup'
export {Navbar,Hero,Categories,Main,GetInTouch,SaleSection,Footer,LoginForm,Signup}
